"""Streamlit dashboard for TraceWard.

Displays vulnerability risk analysis, structural clusters, defensive attack path,
and smart CSP remediation schedule.
Supports both live pipeline artifacts and contract-compatible mock fallbacks.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.csp_solver import solve_csp  # noqa: E402
from src.explainability import (  # noqa: E402
    explain_attack_path,
    explain_patch_priority,
    explain_risk,
)

st.set_page_config(page_title="TraceWard", page_icon="🛡️", layout="wide")

# Fallback mock data
MOCK_CLUSTERS = pd.DataFrame(
    [
        {"vuln_id": "VULN-001", "system_id": "WEB01", "cluster_id": 2},
        {"vuln_id": "VULN-002", "system_id": "DB01", "cluster_id": 1},
        {"vuln_id": "VULN-003", "system_id": "APP01", "cluster_id": 2},
        {"vuln_id": "VULN-004", "system_id": "BACKUP01", "cluster_id": 0},
        {"vuln_id": "VULN-005", "system_id": "VPN01", "cluster_id": 1},
    ]
)

MOCK_RISK = pd.DataFrame(
    [
        {"vuln_id": "VULN-001", "system_id": "WEB01", "actual_risk": "Critical", "predicted_risk": "Critical"},
        {"vuln_id": "VULN-002", "system_id": "DB01", "actual_risk": "High", "predicted_risk": "High"},
        {"vuln_id": "VULN-003", "system_id": "APP01", "actual_risk": "High", "predicted_risk": "Medium"},
        {"vuln_id": "VULN-004", "system_id": "BACKUP01", "actual_risk": "Medium", "predicted_risk": "Medium"},
        {"vuln_id": "VULN-005", "system_id": "VPN01", "actual_risk": "Medium", "predicted_risk": "High"},
    ]
)

MOCK_PATH = explain_attack_path(
    "INTERNET", "DB01", ["INTERNET", "WEB01", "APP01", "DB01"], 8.5
)


@st.cache_data
def load_clusters():
    p = Path("artifacts/kmeans/cluster_assignments.csv")
    if p.exists():
        return pd.read_csv(p), False
    return MOCK_CLUSTERS, True


@st.cache_data
def load_risk():
    p = Path("artifacts/knn/predictions.csv")
    if p.exists():
        return pd.read_csv(p), False
    return MOCK_RISK, True


@st.cache_data
def load_attack_path():
    p = Path("artifacts/astar/attack_path.json")
    if p.exists():
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
            return explain_attack_path(data["start"], data["goal"], data["path"], data.get("total_cost")), False
        except Exception:
            pass
    return MOCK_PATH, True


@st.cache_data
def get_csp_result():
    return solve_csp()


def render_overview(risk_df, csp_result, is_mock_risk):
    st.header("Overview")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Vulnerabilities", len(risk_df))
    col2.metric("Systems", risk_df["system_id"].nunique())
    col3.metric("Risk levels", risk_df["predicted_risk"].nunique())
    col4.metric("Patch tasks", len(csp_result["schedule"]))

    source_tag = "Mock scaffold data" if is_mock_risk else "Live ML pipeline artifacts"
    st.info(f"Data source: **{source_tag}**. The CSP remediation schedule is generated by Backtracking CSP.")


def render_clusters(clusters_df, is_mock):
    st.header("Clusters")
    tag = "Mock K-Means output" if is_mock else "Live K-Means cluster assignments"
    st.caption(f"{tag}. Cluster IDs represent structural profiles and are not severity labels.")
    st.dataframe(clusters_df.head(100), width="stretch", hide_index=True)
    summary = (
        clusters_df.groupby("cluster_id")
        .agg(vulnerabilities=("vuln_id", "count"), systems=("system_id", "nunique"))
        .reset_index()
    )
    st.subheader("Cluster summary")
    st.dataframe(summary, width="stretch", hide_index=True)


def render_risk_prediction(risk_df, clusters_df, is_mock):
    st.header("Risk Prediction")
    tag = "Mock KNN output" if is_mock else "Live KNN predictions"
    st.caption(f"{tag} using the agreed 7-feature security contract.")
    st.dataframe(risk_df.head(100), width="stretch", hide_index=True)

    vuln_list = risk_df["vuln_id"].tolist()
    if vuln_list:
        selected = st.selectbox("Explain vulnerability", vuln_list[:50])
        row = risk_df.loc[risk_df["vuln_id"] == selected].iloc[0]
        cluster_matches = clusters_df.loc[clusters_df["vuln_id"] == selected]
        cluster_id = int(cluster_matches.iloc[0]["cluster_id"]) if not cluster_matches.empty else None

        explanation = explain_risk(
            row["vuln_id"],
            row["system_id"],
            row["predicted_risk"],
            risk_factors=[f"Predicted class: {row['predicted_risk']}", f"System: {row['system_id']}"],
            cluster_id=cluster_id,
        )
        st.write(explanation["summary"])
        for factor in explanation["evidence"]:
            st.write(f"- {factor}")
        st.caption(explanation["cluster_context"])


def render_attack_path(attack_path_info, is_mock):
    st.header("Attack Graph / Path")
    tag = "Mock A* path" if is_mock else "Live A* attack path"
    st.caption(f"{tag} for defensive network-risk analysis.")
    st.code(" → ".join(attack_path_info["path"]))
    st.metric("Total path cost", attack_path_info["total_cost"])
    st.write(attack_path_info["summary"])
    st.caption(attack_path_info["human_readable"])


def render_patch_plan(csp_result):
    st.header("Patch Plan")
    st.caption("Feasible schedule produced by Backtracking CSP; respects team and time slot constraints.")
    schedule = pd.DataFrame(csp_result["schedule"])
    st.dataframe(schedule, width="stretch", hide_index=True)

    selected = st.selectbox("Explain patch task", schedule["vuln_id"].tolist(), key="patch_task")
    row = schedule.loc[schedule["vuln_id"] == selected].iloc[0]
    explanation = explain_patch_priority(
        row["vuln_id"],
        row["system_id"],
        row["priority"],
        reason="Priority comes from upstream risk rating.",
        scheduled_slot=row["time_slot"],
        team=row["team"],
    )
    st.write(explanation["summary"])

    with st.expander("CSP contract"):
        st.write("Variables", csp_result["variables"])
        st.write("Domains", csp_result["domains"])
        st.write("Constraints")
        for constraint in csp_result["constraints"]:
            st.write(f"- {constraint}")


def render_what_if():
    st.header("What-If Analysis")
    st.caption("Scenario analysis controls. Demonstrates interactive simulation capability.")
    priority = st.selectbox("Scenario", ["Current baseline priorities", "Upgrade VULN-004 to High", "Simulate Zero-Day on DB01"])
    extra_team = st.checkbox("Add temporary Database Team slot")
    st.write(f"Active Scenario: **{priority}**")
    st.write(f"Additional capacity enabled: **{'Yes' if extra_team else 'No'}**")
    st.info("Scenario simulation provides defensive risk forecasting before committing remediation resources.")


def main():
    st.title("🛡️ TraceWard")
    st.caption("Cyber Risk Analysis • Attack Path Detection • Smart Remediation Planning")

    clusters_df, is_mock_clusters = load_clusters()
    risk_df, is_mock_risk = load_risk()
    attack_path_info, is_mock_path = load_attack_path()
    csp_result = get_csp_result()

    tabs = st.tabs(
        [
            "Overview",
            "Clusters",
            "Risk Prediction",
            "Attack Graph/Path",
            "Patch Plan",
            "What-If Analysis",
        ]
    )

    with tabs[0]:
        render_overview(risk_df, csp_result, is_mock_risk)
    with tabs[1]:
        render_clusters(clusters_df, is_mock_clusters)
    with tabs[2]:
        render_risk_prediction(risk_df, clusters_df, is_mock_risk)
    with tabs[3]:
        render_attack_path(attack_path_info, is_mock_path)
    with tabs[4]:
        render_patch_plan(csp_result)
    with tabs[5]:
        render_what_if()


if __name__ == "__main__":
    main()
