"""Streamlit dashboard for TraceWard.

Displays vulnerability risk analysis, structural clusters, defensive attack path,
and smart CSP remediation schedule.
Supports both live pipeline artifacts and contract-compatible mock fallbacks.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.csp_solver import CSPCase, VulnerabilityTask, solve_csp  # noqa: E402
from src.explainability import (  # noqa: E402
    explain_attack_path,
    explain_patch_priority,
    explain_risk,
)
from src.knn_classifier import (  # noqa: E402
    FEATURE_COLUMNS,
    predict_single_vulnerability,
)
from src.what_if_simulation import simulate_patch_impact  # noqa: E402

st.set_page_config(page_title="TraceWard", page_icon="🛡️", layout="wide")

try:
    from dashboard.ui import inject_dark_theme
    inject_dark_theme()
except Exception:
    pass


# Fallback mock data
MOCK_CLUSTERS = pd.DataFrame(
    [
        {"vuln_id": "VULN-001", "system_id": "WEB01", "cluster_id": 2},
        {"vuln_id": "VULN-002", "system_id": "DB01", "cluster_id": 1},
        {"vuln_id": "VULN-003", "system_id": "APP01", "cluster_id": 2},
        {"vuln_id": "VULN-004", "system_id": "BACKUP01", "cluster_id": 0},
        {"vuln_id": "VULN-005", "system_id": "VPN01", "cluster_id": 1},
    ]
)

MOCK_RISK = pd.DataFrame(
    [
        {"vuln_id": "VULN-001", "system_id": "WEB01", "actual_risk": "Critical", "predicted_risk": "Critical"},
        {"vuln_id": "VULN-002", "system_id": "DB01", "actual_risk": "High", "predicted_risk": "High"},
        {"vuln_id": "VULN-003", "system_id": "APP01", "actual_risk": "High", "predicted_risk": "Medium"},
        {"vuln_id": "VULN-004", "system_id": "BACKUP01", "actual_risk": "Medium", "predicted_risk": "Medium"},
        {"vuln_id": "VULN-005", "system_id": "VPN01", "actual_risk": "Medium", "predicted_risk": "High"},
    ]
)

MOCK_PATH = explain_attack_path(
    "INTERNET", "DB01", ["INTERNET", "WEB01", "APP01", "DB01"], 8.5
)


@st.cache_data
def load_clusters():
    p = Path("artifacts/kmeans/cluster_assignments.csv")
    if p.exists():
        return pd.read_csv(p), False
    return MOCK_CLUSTERS, True


@st.cache_data
def load_risk():
    p = Path("artifacts/knn/predictions.csv")
    if p.exists():
        return pd.read_csv(p), False
    return MOCK_RISK, True


@st.cache_data
def load_attack_path():
    p = Path("artifacts/astar/attack_path.json")
    if p.exists():
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
            return explain_attack_path(data["start"], data["goal"], data["path"], data.get("total_cost")), False
        except Exception:
            pass
    return MOCK_PATH, True


@st.cache_data
def get_csp_result():
    return solve_csp()


def render_overview(risk_df, csp_result, is_mock_risk):
    st.header("Overview")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Vulnerabilities", len(risk_df))
    col2.metric("Systems", risk_df["system_id"].nunique())
    col3.metric("Risk levels", risk_df["predicted_risk"].nunique())
    col4.metric("Patch tasks", len(csp_result["schedule"]))

    source_tag = "Mock scaffold data" if is_mock_risk else "Live ML pipeline artifacts"
    st.info(f"Data source: **{source_tag}**. The CSP remediation schedule is generated by Backtracking CSP.")


def render_clusters(clusters_df, is_mock):
    st.header("Clusters")
    tag = "Mock K-Means output" if is_mock else "Live K-Means cluster assignments"
    st.caption(f"{tag}. Cluster IDs represent structural profiles and are not severity labels.")
    st.dataframe(clusters_df.head(100), width="stretch", hide_index=True)
    summary = (
        clusters_df.groupby("cluster_id")
        .agg(vulnerabilities=("vuln_id", "count"), systems=("system_id", "nunique"))
        .reset_index()
    )
    st.subheader("Cluster summary")
    st.dataframe(summary, width="stretch", hide_index=True)


def render_risk_prediction(risk_df, clusters_df, is_mock):
    st.header("Risk Prediction")
    tag = "Mock KNN output" if is_mock else "Live KNN predictions"
    st.caption(f"{tag} using the agreed 7-feature security contract.")
    st.dataframe(risk_df.head(100), width="stretch", hide_index=True)

    vuln_list = risk_df["vuln_id"].tolist()
    if vuln_list:
        selected = st.selectbox("Explain vulnerability", vuln_list[:50])
        row = risk_df.loc[risk_df["vuln_id"] == selected].iloc[0]
        cluster_matches = clusters_df.loc[clusters_df["vuln_id"] == selected]
        cluster_id = int(cluster_matches.iloc[0]["cluster_id"]) if not cluster_matches.empty else None

        explanation = explain_risk(
            row["vuln_id"],
            row["system_id"],
            row["predicted_risk"],
            risk_factors=[f"Predicted class: {row['predicted_risk']}", f"System: {row['system_id']}"],
            cluster_id=cluster_id,
        )
        st.write(explanation["summary"])
        for factor in explanation["evidence"]:
            st.write(f"- {factor}")
        st.caption(explanation["cluster_context"])

    st.markdown("---")
    st.subheader("Interactive Model Inference (Predict New Vulnerability)")
    st.caption("Submit custom security features to the fitted KNN pipeline in real-time.")

    with st.form("new_vuln_prediction_form"):
        col1, col2, col3 = st.columns(3)
        with col1:
            ac_map = {"Low (0)": 0, "High (1)": 1}
            ac_choice = st.selectbox("Attack Complexity", list(ac_map.keys()), index=0)
            pr_map = {"None (0)": 0, "Low (1)": 1, "High (2)": 2}
            pr_choice = st.selectbox("Privileges Required", list(pr_map.keys()), index=0)
            ui_map = {"None (0)": 0, "Required (1)": 1}
            ui_choice = st.selectbox("User Interaction", list(ui_map.keys()), index=0)
        with col2:
            ci_map = {"None (0)": 0, "Low (1)": 1, "High (2)": 2}
            ci_choice = st.selectbox("Confidentiality Impact", list(ci_map.keys()), index=2)
            ii_choice = st.selectbox("Integrity Impact", list(ci_map.keys()), index=2)
            ai_choice = st.selectbox("Availability Impact", list(ci_map.keys()), index=2)
        with col3:
            exp_prob = st.slider("Exploit Probability", min_value=0.0, max_value=1.0, value=0.85, step=0.05)
            target_sys = st.selectbox("Target System", ["WEB01", "APP01", "AUTH01", "VPN01", "EMP01", "DB01", "BACKUP01"])
            submit_pred = st.form_submit_button("Predict Risk Class")

    if submit_pred:
        custom_features = {
            "attack_complexity": ac_map[ac_choice],
            "privileges_required": pr_map[pr_choice],
            "user_interaction": ui_map[ui_choice],
            "confidentiality_impact": ci_map[ci_choice],
            "integrity_impact": ci_map[ii_choice],
            "availability_impact": ci_map[ai_choice],
            "exploit_probability": exp_prob,
        }
        try:
            pred_result = predict_single_vulnerability(custom_features)
            p_class = pred_result["predicted_risk"]
            p_probs = pred_result.get("probabilities", {})

            st.success(f"Predicted Risk Level: **{p_class}**")
            p_cols = st.columns(4)
            for idx, c_name in enumerate(["Low", "Medium", "High", "Critical"]):
                c_vote = p_probs.get(c_name, 0.0)
                p_cols[idx].metric(f"{c_name} Vote Share", f"{c_vote * 100:.1f}%")

            st.caption(
                "Metric definition: Values represent KNN neighbor vote shares (fraction of K=3 nearest training instances "
                "assigned to each class). These are uncalibrated vote shares, not Bayesian posterior probabilities or certainty guarantees."
            )

            exp = explain_risk(
                "NEW-VULN-PRED",
                target_sys,
                p_class,
                risk_factors=[
                    f"Attack Complexity: {ac_choice}",
                    f"Privileges Required: {pr_choice}",
                    f"Exploit Probability: {exp_prob:.2f}",
                    f"Impact: C={ci_choice}, I={ii_choice}, A={ai_choice}",
                ],
            )
            st.info(
                f"**Explanation:** Classification decision is **{p_class}** based on distance in the 7-dimensional "
                "standardized feature space to nearest training instances. Distance metrics reflect geometric similarity "
                "under CVSS metric distributions, not single-feature causal relationships."
            )
        except Exception as e:
            st.error(f"Inference failed: {e}")


def render_attack_path(attack_path_info, is_mock):
    st.header("Attack Graph / Path")
    tag = "Mock A* path" if is_mock else "Live A* attack path"
    st.caption(f"{tag} for defensive network-risk analysis.")
    st.code(" → ".join(attack_path_info["path"]))
    st.metric("Total path cost", attack_path_info["total_cost"])
    st.write(attack_path_info["summary"])
    st.caption(attack_path_info["human_readable"])


def render_patch_plan(csp_result):
    st.header("Patch Plan")
    st.caption("Feasible schedule produced by Backtracking CSP; respects team and time slot constraints.")

    if csp_result.get("status") == "infeasible":
        st.error(f"⚠️ CSP Infeasibility Detected: {csp_result.get('message', 'No feasible schedule exists.')}")
        return

    meta = csp_result.get("metadata", {})
    if meta.get("source") == "live_pipeline":
        c1, c2, c3 = st.columns(3)
        c1.metric("Scheduled Tasks", meta.get("selected_task_count", len(csp_result["schedule"])))
        c2.metric("Pending Backlog", meta.get("pending_backlog_count", 0))
        c3.metric("Evaluated Predictions", meta.get("total_evaluated_vulnerabilities", len(csp_result["schedule"])))
        st.caption(
            f"**Selection Rule:** {meta.get('selection_rule', 'Attack-path aligned priority tasks.')} "
            "Remediation is partitioned into operational windows; non-scheduled items remain in the pending queue."
        )

    schedule = pd.DataFrame(csp_result["schedule"])
    st.dataframe(schedule, width="stretch", hide_index=True)

    selected = st.selectbox("Explain patch task", schedule["vuln_id"].tolist(), key="patch_task")
    row = schedule.loc[schedule["vuln_id"] == selected].iloc[0]
    explanation = explain_patch_priority(
        row["vuln_id"],
        row["system_id"],
        row["priority"],
        reason="Priority comes from upstream risk rating.",
        scheduled_slot=row["time_slot"],
        team=row["team"],
    )
    st.write(explanation["summary"])

    with st.expander("CSP contract & Infeasibility Handling"):
        st.write("Variables", csp_result["variables"])
        st.write("Domains", csp_result["domains"])
        st.write("Constraints")
        for constraint in csp_result["constraints"]:
            st.write(f"- {constraint}")

        st.markdown("---")
        st.caption("Test constraint enforcement: Simulate overconstrained schedule (2 tasks for 1 team in 1 slot)")
        if st.button("Test Infeasible Scenario"):
            infeasible_case = CSPCase(
                vulnerabilities=(
                    VulnerabilityTask("VULN-001", "WEB01", "Critical", "Web Team"),
                    VulnerabilityTask("VULN-003", "APP01", "High", "Web Team"),
                ),
                available_teams=("Web Team",),
                time_slots=("Mon 09:00",),
            )
            inf_res = solve_csp(infeasible_case, raise_on_infeasible=False)
            if inf_res["status"] == "infeasible":
                st.warning(f"Solver correctly identified infeasibility: {inf_res['message']}")


def render_what_if():
    st.header("What-If Scenario Simulation (System-Level Hardening)")
    st.caption(
        "Defensive simulation: evaluates the security impact of hardening an entire enterprise system "
        "(multi-vulnerability remediation across a host). "
        "Unit of analysis: Entire system. Operates on an isolated deep copy of the baseline state; "
        "network topology connectivity is preserved and baseline disk artifacts remain unmodified."
    )

    risk_summary_path = Path("artifacts/risk/system_risk_summary.csv")
    if risk_summary_path.exists():
        risk_df = pd.read_csv(risk_summary_path)
        system_list = risk_df["system_id"].tolist()
    else:
        system_list = ["WEB01", "APP01", "DB01", "AUTH01", "VPN01", "EMP01", "BACKUP01"]

    col1, col2 = st.columns(2)
    with col1:
        target_sys = st.selectbox("Target System to Harden / Remediate", system_list, index=0)
    with col2:
        reduction = st.slider("System Risk Reduction (% Hardening)", min_value=10, max_value=90, value=50, step=10)

    col_btn1, col_btn2 = st.columns([1, 4])
    run_sim = col_btn1.button("Run Simulation", type="primary")
    reset_sim = col_btn2.button("Restore Baseline")

    if reset_sim:
        st.session_state.pop("sim_result", None)
        st.info("Baseline state active. No simulation changes applied.")
        return

    if run_sim or "sim_result" in st.session_state:
        if run_sim:
            try:
                res = simulate_patch_impact(
                    target_sys,
                    risk_reduction_factor=reduction / 100.0,
                    start_node="INTERNET",
                    goal_node="DB01",
                )
                st.session_state["sim_result"] = res
            except Exception as e:
                st.error(f"Simulation failed: {e}")
                return

        res = st.session_state.get("sim_result")
        if res:
            st.subheader(f"Simulation Results: Patching {res['target_system']} (-{reduction}%)")
            st.info(f"**Impact Summary:** {res['explanation']}")

            m1, m2, m3 = st.columns(3)
            base_r = res["baseline"]["system_risk"]["normalized_risk"]
            sim_r = res["simulated"]["system_risk"]["normalized_risk"]
            r_delta = res["deltas"]["risk_reduction"]
            m1.metric("System Risk", f"{sim_r:.3f}", f"-{r_delta:.3f}", delta_color="inverse")

            base_cost = res["baseline"]["path_cost"]
            sim_cost = res["simulated"]["path_cost"]
            c_delta = res["deltas"]["path_cost_increase"]
            m2.metric("Adversary Traversal Cost", f"{sim_cost:.2f}", f"+{c_delta:.2f} (Hardened)")

            path_status = "Rerouted" if res["deltas"]["path_diverted"] else "Maintained (Hardened)"
            m3.metric("Attack Path Status", path_status)

            st.write("**Attack Path Comparison:**")
            col_p1, col_p2 = st.columns(2)
            with col_p1:
                st.caption("Baseline A* Path")
                st.code(" → ".join(res["baseline"]["attack_path"]))
            with col_p2:
                st.caption(f"Simulated A* Path (after patching {res['target_system']})")
                st.code(" → ".join(res["simulated"]["attack_path"]))

            with st.expander("System Risk Comparison (Before vs. After)"):
                st.dataframe(res["simulated_risk_df"], width="stretch", hide_index=True)


def main():
    st.title("🛡️ TraceWard")
    st.caption("Cyber Risk Analysis • Attack Path Detection • Smart Remediation Planning")

    clusters_df, is_mock_clusters = load_clusters()
    risk_df, is_mock_risk = load_risk()
    attack_path_info, is_mock_path = load_attack_path()
    csp_result = get_csp_result()

    tabs = st.tabs(
        [
            "Overview",
            "Clusters",
            "Risk Prediction",
            "Attack Graph/Path",
            "Patch Plan",
            "What-If Analysis",
        ]
    )

    with tabs[0]:
        render_overview(risk_df, csp_result, is_mock_risk)
    with tabs[1]:
        render_clusters(clusters_df, is_mock_clusters)
    with tabs[2]:
        render_risk_prediction(risk_df, clusters_df, is_mock_risk)
    with tabs[3]:
        render_attack_path(attack_path_info, is_mock_path)
    with tabs[4]:
        render_patch_plan(csp_result)
    with tabs[5]:
        render_what_if()


if __name__ == "__main__":
    main()
